export module allegro:mouse_cursor;

import <allegro5/mouse_cursor.h>;
import :base;
import :bitmap;
import :display;
import :memory;


namespace ALLEGRO
{
	export using MOUSE_CURSOR_DATA = ALLEGRO_MOUSE_CURSOR;
	export using MOUSE_CURSOR = ALLEGRO::OBJECT_TYPE;
	export using SYSTEM_MOUSE_CURSOR = ALLEGRO_SYSTEM_MOUSE_CURSOR;

	export enum
	{
		SYSTEM_MOUSE_CURSOR_NONE = ALLEGRO_SYSTEM_MOUSE_CURSOR_NONE,
		SYSTEM_MOUSE_CURSOR_DEFAULT = ALLEGRO_SYSTEM_MOUSE_CURSOR_DEFAULT,
		SYSTEM_MOUSE_CURSOR_ARROW = ALLEGRO_SYSTEM_MOUSE_CURSOR_ARROW,
		SYSTEM_MOUSE_CURSOR_BUSY = ALLEGRO_SYSTEM_MOUSE_CURSOR_BUSY,
		SYSTEM_MOUSE_CURSOR_QUESTION = ALLEGRO_SYSTEM_MOUSE_CURSOR_QUESTION,
		SYSTEM_MOUSE_CURSOR_EDIT = ALLEGRO_SYSTEM_MOUSE_CURSOR_EDIT,
		SYSTEM_MOUSE_CURSOR_MOVE = ALLEGRO_SYSTEM_MOUSE_CURSOR_MOVE,
		SYSTEM_MOUSE_CURSOR_RESIZE_N = ALLEGRO_SYSTEM_MOUSE_CURSOR_RESIZE_N,
		SYSTEM_MOUSE_CURSOR_RESIZE_W = ALLEGRO_SYSTEM_MOUSE_CURSOR_RESIZE_W,
		SYSTEM_MOUSE_CURSOR_RESIZE_S = ALLEGRO_SYSTEM_MOUSE_CURSOR_RESIZE_S,
		SYSTEM_MOUSE_CURSOR_RESIZE_E = ALLEGRO_SYSTEM_MOUSE_CURSOR_RESIZE_E,
		SYSTEM_MOUSE_CURSOR_RESIZE_NW = ALLEGRO_SYSTEM_MOUSE_CURSOR_RESIZE_NW,
		SYSTEM_MOUSE_CURSOR_RESIZE_SW = ALLEGRO_SYSTEM_MOUSE_CURSOR_RESIZE_SW,
		SYSTEM_MOUSE_CURSOR_RESIZE_SE = ALLEGRO_SYSTEM_MOUSE_CURSOR_RESIZE_SE,
		SYSTEM_MOUSE_CURSOR_RESIZE_NE = ALLEGRO_SYSTEM_MOUSE_CURSOR_RESIZE_NE,
		SYSTEM_MOUSE_CURSOR_PROGRESS = ALLEGRO_SYSTEM_MOUSE_CURSOR_PROGRESS,
		SYSTEM_MOUSE_CURSOR_PRECISION = ALLEGRO_SYSTEM_MOUSE_CURSOR_PRECISION,
		SYSTEM_MOUSE_CURSOR_LINK = ALLEGRO_SYSTEM_MOUSE_CURSOR_LINK,
		SYSTEM_MOUSE_CURSOR_ALT_SELECT = ALLEGRO_SYSTEM_MOUSE_CURSOR_ALT_SELECT,
		SYSTEM_MOUSE_CURSOR_UNAVAILABLE = ALLEGRO_SYSTEM_MOUSE_CURSOR_UNAVAILABLE,
		SYSTEM_MOUSE_CURSOR_COUNT = ALLEGRO_NUM_SYSTEM_MOUSE_CURSORS
	};
}

namespace al
{
	namespace internal
	{
		export inline void destroy_mouse_cursor(ALLEGRO::MOUSE_CURSOR_DATA* data)
		{
			al_destroy_mouse_cursor(data);
		}
	}

	export inline ALLEGRO::MOUSE_CURSOR create_mouse_cursor(ALLEGRO::BITMAP& sprite, ALLEGRO::POINT<int32_t> focus)
	{
		return ALLEGRO::MOUSE_CURSOR(al_create_mouse_cursor((ALLEGRO::BITMAP_DATA*)sprite.get(), focus.x, focus.y), internal::destroy_mouse_cursor);
	}

	export inline bool set_mouse_cursor(ALLEGRO::DISPLAY& display, ALLEGRO::MOUSE_CURSOR& cursor)
	{
		return al_set_mouse_cursor((ALLEGRO::DISPLAY_DATA*)display.get(), (ALLEGRO::MOUSE_CURSOR_DATA*)cursor.get());
	}

	export inline bool set_system_mouse_cursor(ALLEGRO::DISPLAY& display, ALLEGRO::SYSTEM_MOUSE_CURSOR cursor_id)
	{
		return al_set_system_mouse_cursor((ALLEGRO::DISPLAY_DATA*)display.get(), cursor_id);
	}

	export inline bool show_mouse_cursor(ALLEGRO::DISPLAY& display)
	{
		return al_show_mouse_cursor((ALLEGRO::DISPLAY_DATA*)display.get());
	}

	export inline bool hide_mouse_cursor(ALLEGRO::DISPLAY& display)
	{
		return al_hide_mouse_cursor((ALLEGRO::DISPLAY_DATA*)display.get());
	}

}
